server:
  port: 3333
spring:
  application:
    name: 8.Spring-Boot-Actuators
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
        - bean
        - metrices
        
  endpoint:
    shutdown:
      enabled: true