eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1
server:
  port: 4444
spring:
  application:
    name: REST-API-01
  boot:
    admin:
      client:
        url: http://localhost:2222/
        
  cloud:
    compatibility-verifier:
      enabled: false
  zipkin:
    base-url: http://localhost:9411/
    
